-- MySQL Script generated by MySQL Workbench
-- Wed Sep 19 18:10:08 2018
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema bdTicketUnla
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema bdTicketUnla
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `bdTicketUnla` DEFAULT CHARACTER SET utf8 ;
USE `bdTicketUnla` ;

-- -----------------------------------------------------
-- Table `bdTicketUnla`.`usuario`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `bdTicketUnla`.`usuario` ;

CREATE TABLE IF NOT EXISTS `bdTicketUnla`.`usuario` (
  `idUsuario` INT NOT NULL AUTO_INCREMENT,
  `nombre` VARCHAR(45) NULL,
  `contraseña` VARCHAR(45) NULL,
  `email` VARCHAR(45) NULL,
  PRIMARY KEY (`idUsuario`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `bdTicketUnla`.`cliente`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `bdTicketUnla`.`cliente` ;

CREATE TABLE IF NOT EXISTS `bdTicketUnla`.`cliente` (
  `idCliente` INT NOT NULL,
  `dni` INT NULL,
  `nombre` VARCHAR(45) NULL,
  `apellido` VARCHAR(45) NULL,
  `fechaNacimiento` DATE NULL,
  PRIMARY KEY (`idCliente`),
  INDEX `fk_cliente_usuario` (`idCliente` ASC),
  CONSTRAINT `fk_cliente_usuario`
    FOREIGN KEY (`idCliente`)
    REFERENCES `bdTicketUnla`.`usuario` (`idUsuario`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `bdTicketUnla`.`administrador`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `bdTicketUnla`.`administrador` ;

CREATE TABLE IF NOT EXISTS `bdTicketUnla`.`administrador` (
  `idAdministrador` INT NOT NULL,
  PRIMARY KEY (`idAdministrador`),
  INDEX `fk_admin_usuario` (`idAdministrador` ASC),
  CONSTRAINT `fk_administrador_usuario1`
    FOREIGN KEY (`idAdministrador`)
    REFERENCES `bdTicketUnla`.`usuario` (`idUsuario`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `bdTicketUnla`.`vendedor`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `bdTicketUnla`.`vendedor` ;

CREATE TABLE IF NOT EXISTS `bdTicketUnla`.`vendedor` (
  `idVendedor` INT NOT NULL,
  PRIMARY KEY (`idVendedor`),
  INDEX `fk_vendedor_usuario` (`idVendedor` ASC),
  CONSTRAINT `fk_vendedor_usuario1`
    FOREIGN KEY (`idVendedor`)
    REFERENCES `bdTicketUnla`.`usuario` (`idUsuario`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `bdTicketUnla`.`auditorio`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `bdTicketUnla`.`auditorio` ;

CREATE TABLE IF NOT EXISTS `bdTicketUnla`.`auditorio` (
  `idauditorio` INT NOT NULL AUTO_INCREMENT,
  `nombre` VARCHAR(45) NULL,
  `direccion` VARCHAR(45) NULL,
  `capacidad` INT NULL,
  `tipoAuditorio` VARCHAR(45) NULL,
  PRIMARY KEY (`idauditorio`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `bdTicketUnla`.`evento`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `bdTicketUnla`.`evento` ;

CREATE TABLE IF NOT EXISTS `bdTicketUnla`.`evento` (
  `idEvento` INT NOT NULL AUTO_INCREMENT,
  `nombre` VARCHAR(45) NULL,
  `tipoEvento` VARCHAR(45) NULL,
  `idAuditorio` INT NOT NULL,
  PRIMARY KEY (`idEvento`, `idAuditorio`),
  INDEX `fk_evento_auditorio1_idx` (`idAuditorio` ASC),
  CONSTRAINT `fk_evento_auditorio1`
    FOREIGN KEY (`idAuditorio`)
    REFERENCES `bdTicketUnla`.`auditorio` (`idauditorio`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `bdTicketUnla`.`descuento`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `bdTicketUnla`.`descuento` ;

CREATE TABLE IF NOT EXISTS `bdTicketUnla`.`descuento` (
  `porcentajeDescuento` INT NULL,
  `codigo` VARCHAR(45) NULL,
  `idDescuento` INT NOT NULL AUTO_INCREMENT,
  `evento_idEvento` INT NOT NULL,
  PRIMARY KEY (`idDescuento`, `evento_idEvento`),
  INDEX `fk_descuento_evento1_idx` (`evento_idEvento` ASC),
  CONSTRAINT `fk_descuento_evento1`
    FOREIGN KEY (`evento_idEvento`)
    REFERENCES `bdTicketUnla`.`evento` (`idEvento`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `bdTicketUnla`.`funcion`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `bdTicketUnla`.`funcion` ;

CREATE TABLE IF NOT EXISTS `bdTicketUnla`.`funcion` (
  `idfuncion` INT NOT NULL AUTO_INCREMENT,
  `horaFecha` DATETIME NULL,
  `evento_idEvento` INT NOT NULL,
  PRIMARY KEY (`idfuncion`, `evento_idEvento`),
  INDEX `fk_funcion_evento1_idx` (`evento_idEvento` ASC),
  CONSTRAINT `fk_funcion_evento1`
    FOREIGN KEY (`evento_idEvento`)
    REFERENCES `bdTicketUnla`.`evento` (`idEvento`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `bdTicketUnla`.`reserva`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `bdTicketUnla`.`reserva` ;

CREATE TABLE IF NOT EXISTS `bdTicketUnla`.`reserva` (
  `idreserva` INT NOT NULL AUTO_INCREMENT,
  `funcion_idfuncion` INT NOT NULL,
  `cliente_idCliente` INT NOT NULL,
  PRIMARY KEY (`idreserva`, `funcion_idfuncion`, `cliente_idCliente`),
  INDEX `fk_reserva_funcion1_idx` (`funcion_idfuncion` ASC),
  INDEX `fk_reserva_cliente1_idx` (`cliente_idCliente` ASC),
  CONSTRAINT `fk_reserva_funcion1`
    FOREIGN KEY (`funcion_idfuncion`)
    REFERENCES `bdTicketUnla`.`funcion` (`idfuncion`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_reserva_cliente1`
    FOREIGN KEY (`cliente_idCliente`)
    REFERENCES `bdTicketUnla`.`cliente` (`idCliente`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `bdTicketUnla`.`sector`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `bdTicketUnla`.`sector` ;

CREATE TABLE IF NOT EXISTS `bdTicketUnla`.`sector` (
  `idSector` INT NOT NULL AUTO_INCREMENT,
  `tipoSector` VARCHAR(45) NULL,
  `precio` VARCHAR(45) NULL,
  `descripcion` VARCHAR(45) NULL,
  `capacidadTotal` INT NULL,
  `auditorio_idauditorio` INT NOT NULL,
  `reserva_idreserva` INT NULL,
  `funcion_idfuncion` INT NULL,
  PRIMARY KEY (`idSector`, `auditorio_idauditorio`),
  INDEX `fk_sector_auditorio1_idx` (`auditorio_idauditorio` ASC),
  INDEX `fk_sector_reserva1_idx` (`reserva_idreserva` ASC),
  INDEX `fk_sector_funcion1_idx` (`funcion_idfuncion` ASC),
  CONSTRAINT `fk_sector_auditorio1`
    FOREIGN KEY (`auditorio_idauditorio`)
    REFERENCES `bdTicketUnla`.`auditorio` (`idauditorio`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_sector_reserva1`
    FOREIGN KEY (`reserva_idreserva`)
    REFERENCES `bdTicketUnla`.`reserva` (`idreserva`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_sector_funcion1`
    FOREIGN KEY (`funcion_idfuncion`)
    REFERENCES `bdTicketUnla`.`funcion` (`idfuncion`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `bdTicketUnla`.`sectorNoNumerado`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `bdTicketUnla`.`sectorNoNumerado` ;

CREATE TABLE IF NOT EXISTS `bdTicketUnla`.`sectorNoNumerado` (
  `capacidadDisponible` INT NOT NULL,
  `sector_idSector` INT NOT NULL,
  PRIMARY KEY (`capacidadDisponible`, `sector_idSector`),
  INDEX `fk_sectorNoNumerado_sector1_idx` (`sector_idSector` ASC),
  CONSTRAINT `fk_sectorNoNumerado_sector1`
    FOREIGN KEY (`sector_idSector`)
    REFERENCES `bdTicketUnla`.`sector` (`idSector`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `bdTicketUnla`.`sectorNumerado`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `bdTicketUnla`.`sectorNumerado` ;

CREATE TABLE IF NOT EXISTS `bdTicketUnla`.`sectorNumerado` (
  `sector_idSector` INT NOT NULL,
  PRIMARY KEY (`sector_idSector`),
  CONSTRAINT `fk_sectorNumerado_sector1`
    FOREIGN KEY (`sector_idSector`)
    REFERENCES `bdTicketUnla`.`sector` (`idSector`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `bdTicketUnla`.`asiento`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `bdTicketUnla`.`asiento` ;

CREATE TABLE IF NOT EXISTS `bdTicketUnla`.`asiento` (
  `idasiento` INT NOT NULL AUTO_INCREMENT,
  `codigo` VARCHAR(45) NULL,
  `sectorNumerado_idSector` INT NOT NULL,
  PRIMARY KEY (`idasiento`, `sectorNumerado_idSector`),
  INDEX `fk_asiento_sectorNumerado1_idx` (`sectorNumerado_idSector` ASC),
  CONSTRAINT `fk_asiento_sectorNumerado1`
    FOREIGN KEY (`sectorNumerado_idSector`)
    REFERENCES `bdTicketUnla`.`sectorNumerado` (`sector_idSector`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
