-- MySQL Script generated by MySQL Workbench
-- Fri Sep 14 16:58:29 2018
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema bdTicketUnla
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema bdTicketUnla
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `bdTicketUnla` DEFAULT CHARACTER SET utf8 ;
USE `bdTicketUnla` ;

-- -----------------------------------------------------
-- Table `bdTicketUnla`.`usuario`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `bdTicketUnla`.`usuario` ;

CREATE TABLE IF NOT EXISTS `bdTicketUnla`.`usuario` (
  `idUsuario` INT NOT NULL AUTO_INCREMENT,
  `nombre` VARCHAR(45) NULL,
  `contraseña` VARCHAR(45) NULL,
  `email` VARCHAR(45) NULL,
  PRIMARY KEY (`idUsuario`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `bdTicketUnla`.`cliente`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `bdTicketUnla`.`cliente` ;

CREATE TABLE IF NOT EXISTS `bdTicketUnla`.`cliente` (
  `idCliente` INT NOT NULL,
  `dni` INT NULL,
  `nombre` VARCHAR(45) NULL,
  `apellido` VARCHAR(45) NULL,
  `fechaNacimiento` DATE NULL,
  PRIMARY KEY (`idCliente`),
  INDEX `fk_cliente_usuario` (`idCliente` ASC),
  CONSTRAINT `fk_cliente_usuario`
    FOREIGN KEY (`idCliente`)
    REFERENCES `bdTicketUnla`.`usuario` (`idUsuario`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `bdTicketUnla`.`administrador`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `bdTicketUnla`.`administrador` ;

CREATE TABLE IF NOT EXISTS `bdTicketUnla`.`administrador` (
  `idAdministrador` INT NOT NULL,
  PRIMARY KEY (`idAdministrador`),
  INDEX `fk_admin_usuario` (`idAdministrador` ASC),
  CONSTRAINT `fk_administrador_usuario1`
    FOREIGN KEY (`idAdministrador`)
    REFERENCES `bdTicketUnla`.`usuario` (`idUsuario`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `bdTicketUnla`.`vendedor`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `bdTicketUnla`.`vendedor` ;

CREATE TABLE IF NOT EXISTS `bdTicketUnla`.`vendedor` (
  `idVendedor` INT NOT NULL,
  PRIMARY KEY (`idVendedor`),
  INDEX `fk_vendedor_usuario` (`idVendedor` ASC),
  CONSTRAINT `fk_vendedor_usuario1`
    FOREIGN KEY (`idVendedor`)
    REFERENCES `bdTicketUnla`.`usuario` (`idUsuario`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `bdTicketUnla`.`auditorio`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `bdTicketUnla`.`auditorio` ;

CREATE TABLE IF NOT EXISTS `bdTicketUnla`.`auditorio` (
  `idauditorio` INT NOT NULL AUTO_INCREMENT,
  `nombre` VARCHAR(45) NULL,
  `direccion` VARCHAR(45) NULL,
  `capacidad` INT NULL,
  `tipoAuditorio` VARCHAR(45) NULL,
  PRIMARY KEY (`idauditorio`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `bdTicketUnla`.`evento`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `bdTicketUnla`.`evento` ;

CREATE TABLE IF NOT EXISTS `bdTicketUnla`.`evento` (
  `idEvento` INT NOT NULL AUTO_INCREMENT,
  `nombre` VARCHAR(45) NULL,
  `tipoEvento` VARCHAR(45) NULL,
  `idAuditorio` INT NOT NULL,
  PRIMARY KEY (`idEvento`, `idAuditorio`),
  INDEX `fk_evento_auditorio1_idx` (`idAuditorio` ASC),
  CONSTRAINT `fk_evento_auditorio1`
    FOREIGN KEY (`idAuditorio`)
    REFERENCES `bdTicketUnla`.`auditorio` (`idauditorio`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `bdTicketUnla`.`descuento`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `bdTicketUnla`.`descuento` ;

CREATE TABLE IF NOT EXISTS `bdTicketUnla`.`descuento` (
  `porcentajeDescuento` INT NULL,
  `codigo` VARCHAR(45) NULL,
  `idDescuento` INT NOT NULL AUTO_INCREMENT,
  `evento_idEvento` INT NOT NULL,
  PRIMARY KEY (`idDescuento`, `evento_idEvento`),
  INDEX `fk_descuento_evento1_idx` (`evento_idEvento` ASC),
  CONSTRAINT `fk_descuento_evento1`
    FOREIGN KEY (`evento_idEvento`)
    REFERENCES `bdTicketUnla`.`evento` (`idEvento`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `bdTicketUnla`.`sector`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `bdTicketUnla`.`sector` ;

CREATE TABLE IF NOT EXISTS `bdTicketUnla`.`sector` (
  `idSector` INT NOT NULL AUTO_INCREMENT,
  `tipoSector` VARCHAR(45) NULL,
  `precio` VARCHAR(45) NULL,
  `descripcion` VARCHAR(45) NULL,
  `capacidadTotal` INT NULL,
  `auditorio_idauditorio` INT NOT NULL,
  PRIMARY KEY (`idSector`, `auditorio_idauditorio`),
  INDEX `fk_sector_auditorio1_idx` (`auditorio_idauditorio` ASC),
  CONSTRAINT `fk_sector_auditorio1`
    FOREIGN KEY (`auditorio_idauditorio`)
    REFERENCES `bdTicketUnla`.`auditorio` (`idauditorio`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;

